name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run
        required: true
        type: choice
        options:
          - all

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: copy source code
        uses: actions/checkout@v4
      - name: setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
